### ISSUE TITLE
Updated GHG FBS are not precise for waste sectors

### ISSUE THREAD

**Issue by bl-young** [USEPA/HIO#16]
The new FBS (changed [here](https://github.com/USEPA/HIO/commit/75160052be068cc7129d09f2f6b8bf73b68f3192)) use a [BEA_detail_target](https://github.com/USEPA/flowsa/blob/master/flowsa/methods/flowbysectormethods/BEA_detail_target.yaml) schema, so waste only gets assigned to `562`. This limits our ability to disaggregate specific waste sectors as was designed for say `USEEIO-Waste-Disagg`

**Comment by bl-young** [comment]
i.e., running this chunk for USEEIO-Waste-Disagg gives a much lower result for landfilling of food waste, for instance.
https://github.com/USEPA/HIO/blob/cae709afa4e522d7544dc213104ee33424b2197b/useeior/demo_HIO_models.Rmd#L64-L109

**Comment by bl-young** [comment]
once https://github.com/USEPA/flowsa/pull/396 is pulled in we can regenerate the GHG files to resolve this. 

@WesIngwersen please let me know the ramifications for any published GHG models - do we  want to recreate all (2012-2020) GHG m2 parquets?

**Comment by WesIngwersen** [comment]
Yes. I will communicate more separately on that.

**Comment by bl-young** [comment]
Confirming that in rerunning these models with the revised FBS fixes this issue. Results look very similar to before. I will close once the FBS are finalized and updated in the model specs
