### ISSUE TITLE
Concrete vs food FBS unit difference

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/HIO#9]
The [FBS dataset used in DisaggWIOConcrete ](https://github.com/USEPA/HIO/blob/50021fa8d3442be6c6fd20b73f26617e025f0338/useeior/DisaggWIOConcrete.yml#L5)is in short tons (at least purportedly in the FBS).
This makes the rows/columns using this data to be in short tons.

This in in contrast with the [food waste FBS ](https://github.com/USEPA/HIO/blob/50021fa8d3442be6c6fd20b73f26617e025f0338/useeior/DisaggWIOFoodWaste.yml#L4) used in the same HIO model 
where the units are in kg

**Comment by bl-young** [comment]
@catherinebirney I would have thought that [this line in flowbysector](https://github.com/USEPA/flowsa/blob/waste/flowsa/flowbysector.py#L422) would lead to standardized units via [this line in clean_df](https://github.com/USEPA/flowsa/blob/069eb3b547ec8e970398aec3de2a342a8699888b/flowsa/dataclean.py#L32-L34).
But i think that perhaps should be a variable and not a string. Can you confirm?

**Comment by bl-young** [comment]
Also I am having trouble running the fbs for CDD_concrete_national_2014 now. I assume something was introduced over the last month.
```
  File C:/Users/BYoung/Desktop/Spyder/flowsa/src/flowsa/flowsa/data_source_scripts/EPA_CDDPath.py:190 in <module>
    flowsa.flowbysector.main(method='CDD_concrete_national_2014')

  File ~\Desktop\Spyder\flowsa\src\flowsa\flowsa\flowbysector.py:370 in main
    sector_list = get_sector_list(

  File ~\Desktop\Spyder\flowsa\src\flowsa\flowsa\sectormapping.py:430 in get_sector_list
    cw_melt = cw.melt(

  File ~\Anaconda3\lib\site-packages\pandas\core\frame.py:8440 in melt
    return melt(

  File ~\Anaconda3\lib\site-packages\pandas\core\reshape\melt.py:77 in melt
    raise KeyError(

KeyError: "The following 'id_vars' are not present in the DataFrame: ['NAICS_8']"
```
Can I reassign to you @catherinebirney since I expect you may be able to track this down more quickly?

**Comment by catherinebirney** [comment]
@bl-young I [updated](https://github.com/USEPA/flowsa/commit/1ec14ce45841bd227e59edbda5a79d10dfcee170) the target subset level, so CDD FBS now runs.

I fixed the error that led to units not being standardized a few weeks ago - so rerunning the FBS now corrected the units to kg. I added `CDD_concrete_national_2014_v1.2.4_069eb3b.parquet` to the v1.2.4 folder on sharepoint

**Comment by bl-young** [comment]
thank you! I had lost track of the NAICS/mapping changes

**Comment by bl-young** [comment]
ok this latest FBS has some unexpected differences compared to the prior one (besides just the units) so I will need to look closer before we update the model

**Comment by bl-young** [comment]
reran locally and updated on sharepoint. We will use: `CDD_concrete_national_2014_v1.2.4_1ec14ce.parquet` thanks @catherinebirney
